version: '3.8'
services:
  postgres:
    container_name: median_postgres
    image: postgres:16
    restart: always
    env_file:
      '.env'
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    container_name: median_pgadmin
    image: dpage/pgadmin4:8
    env_file:
      - '.env'
    ports:
      - '5050:80'
    depends_on:
      postgres:
        condition: 'service_healthy'